---
- name: Configure Apache.
  lineinfile:
    dest: "{{ apache_server_root }}/conf/{{ apache_daemon }}.conf"
    regexp: "^Listen "
    line: "Listen "
    state: absent
  notify: restart apache

- name: Configure port.conf
  template:
    src: "port.conf.j2"
    dest: "{{ apache_server_root }}/conf/port.conf"
  notify: restart apache

- name: Include port.conf
  lineinfile:
    dest: "{{ apache_server_root }}/conf/{{ apache_daemon }}.conf"
    insertafter: "^#Listen"
    line: "Include conf/port.conf"
  notify: restart apache

- name: Check whether certificates defined in vhosts exist.
  stat: path={{ item.certificate_file }}
  register: apache_ssl_certificates
  with_items: "{{ apache_vhosts_ssl }}"

- name: Add apache vhosts configuration.
  template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache_conf_path }}/{{ item.name }}.conf"
    owner: root
    group: root
    mode: 0644
    #validate: "/usr/sbin/httpd -t -f %s"
  notify: restart apache

  with_items:
    - "{{ apache_vhosts }}"
  notify: restart apache
  when: apache_create_vhosts
